/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pbwi.paint;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;


public class PaintPanel extends javax.swing.JPanel {
    private static PaintPanel instance = null;
    private Class shapeClass;
    
    public void setShapeClass(Class shapeClass) {
        this.shapeClass = shapeClass;
    }
    int x,y;
    /**
     * Creates new form PaintPanel
     */
    public PaintPanel() {
        initComponents();
        this.addMouseListener(new MouseAdapter() {
                public void mousePressed(MouseEvent e) {
                x = e.getX();
                y = e.getY();

                System.out.println(x + " " + y);
                repaint();
                }
        });
    }
    public static PaintPanel getInstance() {
        if(instance == null) {
                        instance = new PaintPanel();
        }
        return instance;
    }
    
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        
        Shape shape = null;
        if(shapeClass == Rectangle.class) {
            shape = new Rectangle(50,50,x-25,y-25);
        } else if (shapeClass == Ellipse.class) {
            shape = new Ellipse(50,50,x-25,y-25);
        } else if (shapeClass == Line.class) {
            shape = new Line(x-25,y,x+25,y);
        } else if (shapeClass == Polygon.class)
        {
             int xpoints[] = {25, 145, 25, 145, 25};
             int ypoints[] = {25, 25, 145, 145, 25};
             int npoints = 5;
             
             shape = new Polygon(npoints, xpoints, ypoints);
        }
        if(shape != null)
            shape.draw(g);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
